- name: Setup local mac for work
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Gather current user
      set_fact:
        current_user: "{{ ansible_env.USER }}"

    - name: Install Homebrew (if not installed)
      command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      args:
        creates: /usr/local/bin/brew
      register: homebrew_installed
      changed_when: false  # This task won't be considered changed if Homebrew is already installed

    - name: Read application names from file
      include_vars:
        file: applications.yml
        name: app

    - name: Install applications via Homebrew
      community.general.homebrew:
        name: "{{ app.core_applications | join(',') }}"
        state: latest
        update_homebrew: true
      when: homebrew_installed.changed | default(true)  # Only run if Homebrew was installed or updated

    - name: Install applications via Homebrew Cask
      community.general.homebrew_cask:
        name: "{{ app.cask_applications | join(',') }}"
        state: latest
        greedy: true
        accept_external_apps: true
      ignore_errors: yes
      when: homebrew_installed.changed | default(true)  # Only run if Homebrew was installed or updated

    - name: "Install from Mac app store"
      shell: mas install {{ item }}
      with_items:
        - 497799835 # xcode
      when: homebrew_installed.changed | default(true)  # Only run if Homebrew was installed or updated

    - name: Install Oh My Zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: "/Users/{{ current_user }}/.oh-my-zsh"
      become: yes
      register: oh_my_zsh_installed
      changed_when: false  # This task won't be considered changed if Oh My Zsh is already installed

    - name: Install Powerlevel10k
      become: yes
      git:
        repo: "https://github.com/romkatv/powerlevel10k.git"
        dest: "/Users/{{ current_user }}/.oh-my-zsh/custom/themes/powerlevel10k"
      when: oh_my_zsh_installed.changed | default(true)  # Only run if Oh My Zsh was installed or updated

    - name: Configure Powerlevel10k in .zshrc
      become: yes
      lineinfile:
        path: "/Users/{{ current_user }}/.zshrc"
        line: "ZSH_THEME='powerlevel10k/powerlevel10k'"
        insertafter: EOF
      when: oh_my_zsh_installed.changed | default(true)  # Only run if Oh My Zsh was installed or updated

    - name: Set ZSH as the default shell
      shell: /usr/bin/chsh -s /bin/zsh {{ current_user }}
      become: yes

    - name: Configure iTerm2 to use Zsh
      command: defaults write com.googlecode.iterm2 Shell /bin/zsh
      become: yes

    - name: Copy dotfiles
      become: yes
      copy:
        src: "dotfiles/*"
        dest: "/Users/{{ current_user }}/"
        owner: "{{ current_user }}"
        mode: "0644"

    - name: Copy iTerm2 profile
      become: yes
      copy:
        src: "settingsfiles/itermProfiles.json"
        dest: "/Users/{{ current_user }}/Library/Application Support/iTerm2/DynamicProfiles/Profiles.json"
        owner: "{{ current_user }}"
        mode: "0644"

    - name: Run macos config
      shell: source /Users/{{ current_user }}/.macos
      become: yes
